# Generated by Django 5.1.2 on 2024-10-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_perfil_areas_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaexperticia',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_experticia', to='perfil.perfil'),
        ),
        migrations.AlterField(
            model_name='informacionadicional',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion_adicional', to='perfil.perfil'),
        ),
    ]
