# Generated by Django 5.1.2 on 2024-10-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'foco_innovacion',
            },
        ),
        migrations.CreateModel(
            name='InnovationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_innovacion',
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_idea', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('recursos_requeridos', models.IntegerField(blank=True, null=True)),
                ('palabras_claves', models.CharField(blank=True, max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('archivos_multimedia', models.FileField(blank=True, null=True, upload_to='media/')),
                ('id_foco_innovacion', models.ForeignKey(blank=True, db_column='id_foco_innovacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.innovationfocus')),
                ('id_tipo_innovacion', models.ForeignKey(blank=True, db_column='id_tipo_innovacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='ideas.innovationtype')),
            ],
            options={
                'verbose_name': 'Ideas',
                'db_table': 'idea',
                'ordering': ['titulo'],
            },
        ),
    ]
